In my environment updatorr fails to update one rutor.org  torrent because one of links on a page contains utf-8  symbols inside an href. Error was:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position ordinal not in range(128):

So I just added ignore errors parameter to url decode function